name: CI Pipeline
on:
  push:
    branches:
      - main
      - stag
  pull_request:
    branches:
      - main
      - stag
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'stag'
        type: choice
        options:
          - main
          - stag

jobs:
  predict-build-error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Predict Build Error
        uses: NT505-P21-KLTN-ThienLM-PhuongQTH/CI-build-failure-prediction-action@main
        with:
        #   api-token: ${{ secrets.API_TOKEN }}
          stop-on-failure: false
          
      - name: Check the result
        run: |
          echo "Prediction: ${{ steps.predict-build-error.outputs.prediction }}"
          echo "Probability: ${{ steps.predict-build-error.outputs.probability }}"
          if [[ "${{ steps.predict-build-error.outputs.prediction }}" == "error" ]]; then
            echo "Build error predicted!"
            exit 1
          else
            echo "Build predicted as successful!"
          fi
      - name: Deploy to Prod
        run: |
          echo "Deploy to production"
